import dash_bootstrap_components as dbc
from dash import dcc, html

from utils import IdHolder, app_data

layout = html.Div(
    children=[
        html.H1(children='Video Game Sales'),
        html.Div(
            children=[
                dbc.Card(
                    dbc.CardBody(
                        [
                            html.H4('Filters', className='card-title'),
                            dbc.InputGroup(
                                [
                                    html.Label('Years'),
                                    dcc.RangeSlider(
                                        id=IdHolder.videogame_sales_years_range.name,
                                        min=app_data.videogame_sales['data'].Year.min(),
                                        max=app_data.videogame_sales['data'].Year.max(),
                                        step=1,
                                        allowCross=False,
                                        pushable=1,
                                        updatemode='drag',
                                        tooltip={
                                            'placement': 'bottom',
                                            'always_visible': True,
                                        },
                                        marks={
                                            i: str(i)
                                            for i in range(
                                                int(
                                                    app_data.videogame_sales['data'].Year.min(),
                                                ),
                                                int(
                                                    app_data.videogame_sales['data'].Year.max(),
                                                )
                                                + 1,
                                                5,
                                            )
                                        },
                                        value=[
                                            app_data.videogame_sales['data'].Year.min(),
                                            app_data.videogame_sales['data'].Year.max(),
                                        ],
                                    ),
                                ],
                            ),
                            dbc.InputGroup(
                                [
                                    dbc.InputGroupText('Region'),
                                    dcc.Dropdown(
                                        options=[
                                            {
                                                'label': 'North America',
                                                'value': 'NA_Sales',
                                            },
                                            {'label': 'Europe', 'value': 'EU_Sales'},
                                            {'label': 'Japan', 'value': 'JP_Sales'},
                                            {'label': 'Other', 'value': 'Other_Sales'},
                                            {
                                                'label': 'Global',
                                                'value': 'Global_Sales',
                                            },
                                        ],
                                        value='Global_Sales',
                                        clearable=False,
                                        id=IdHolder.videogame_sales_region.name,
                                    ),
                                ],
                            ),
                        ],
                        class_name='filter-container',
                    ),
                    style={'position': 'sticky', 'top': '1rem', 'z-index': '1'},
                ),
                html.Div(
                    children=[
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H1(
                                                '$0M',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_amount_title.name,
                                            ),
                                            html.P(
                                                'Video Game Sales',
                                                className='card-text',
                                                id=IdHolder.videogame_sales_amount_description.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H1(
                                                'None',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_top_game_title.name,
                                            ),
                                            html.P(
                                                '$0M',
                                                className='card-text',
                                                id=IdHolder.videogame_sales_top_game_description.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                    ],
                    className='kpi-container',
                ),
                html.Div(
                    children=[
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H1(
                                                'None',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_top_freq_platform_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                className='card-text',
                                                id=IdHolder.videogame_sales_top_freq_platform_description.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H1(
                                                'None',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_trending_genre_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                className='card-text',
                                                id=IdHolder.videogame_sales_trending_genre_description.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                    ],
                    className='kpi-container',
                ),
                html.Div(
                    [
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 1',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_1_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_1.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 2',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_2_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_2.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 3',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_3_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_3.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 4',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_4_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_4.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 5',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_5_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_5.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 6',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_6_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_6.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                    ],
                    className='genre-container',
                ),
                html.Div(
                    [
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 7',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_7_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_7.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 8',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_8_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_8.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 9',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_9_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_9.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 10',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_10_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_10.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 11',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_11_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_11.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                        dbc.Card(
                            dbc.CardBody(
                                [
                                    dbc.Spinner(
                                        [
                                            html.H6(
                                                'Genre 12',
                                                className='card-title',
                                                id=IdHolder.videogame_sales_genre_12_title.name,
                                            ),
                                            html.P(
                                                '0',
                                                id=IdHolder.videogame_sales_genre_12.name,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ),
                    ],
                    className='genre-container',
                ),
                dbc.Card(
                    dbc.CardBody(
                        [
                            html.H4(
                                'Sales by Publisher over the Years',
                                className='card-title',
                                id=IdHolder.videogame_sales_by_publisher_title.name,
                            ),
                            dbc.Spinner(
                                [
                                    dbc.InputGroup(
                                        [
                                            dbc.InputGroupText('Number of Publishers'),
                                            dbc.Input(
                                                type='number',
                                                value=app_data.videogame_sales['top_n_publishers'],
                                                id=IdHolder.videogame_sales_top_n_publishers.name,
                                            ),
                                        ],
                                    ),
                                    dcc.Graph(
                                        id=IdHolder.videogame_sales_by_publisher.name,
                                    ),
                                ],
                            ),
                        ],
                    ),
                ),
                dbc.Card(
                    dbc.CardBody(
                        [
                            html.H4(
                                'Sales by Genre and Publisher',
                                className='card-title',
                                id=IdHolder.videogame_sales_by_genre_title.name,
                            ),
                            dbc.Spinner(
                                dcc.Graph(id=IdHolder.videogame_sales_by_genre.name),
                            ),
                        ],
                    ),
                ),
                dbc.Card(
                    dbc.CardBody(
                        [
                            html.H4(
                                'Top Games by Sales',
                                className='card-title',
                                id=IdHolder.videogame_sales_top_games_title.name,
                            ),
                            dbc.Spinner(
                                [
                                    dbc.InputGroup(
                                        [
                                            dbc.InputGroupText('Number of Games'),
                                            dbc.Input(
                                                type='number',
                                                value=app_data.videogame_sales['top_n_games'],
                                                id=IdHolder.videogame_sales_top_n_games.name,
                                            ),
                                        ],
                                    ),
                                    dcc.Graph(id=IdHolder.videogame_sales_top_games.name),
                                ],
                            ),
                        ],
                    ),
                ),
                dbc.Card(
                    dbc.CardBody(
                        [
                            html.H4(
                                'Sales by Genre over the Years',
                                className='card-title',
                                id=IdHolder.videogame_sales_genre_by_year_title.name,
                            ),
                            dbc.Spinner(
                                dcc.Graph(
                                    id=IdHolder.videogame_sales_genre_by_year.name,
                                ),
                            ),
                        ],
                    ),
                ),
                dbc.Card(
                    dbc.CardBody(
                        [
                            html.H4(
                                'Sales by Genre and Platform',
                                className='card-title',
                                id=IdHolder.videogame_sales_genre_by_platform_title.name,
                            ),
                            dbc.Spinner(
                                dcc.Graph(
                                    id=IdHolder.videogame_sales_genre_by_platform.name,
                                ),
                            ),
                        ],
                    ),
                ),
                dbc.Card(
                    dbc.CardBody(
                        [
                            html.H4(
                                'Sales by Rank over the Years',
                                className='card-title',
                                id=IdHolder.videogame_sales_rank_by_year_title.name,
                            ),
                            dbc.Spinner(
                                dcc.Graph(
                                    id=IdHolder.videogame_sales_rank_by_year.name,
                                ),
                            ),
                        ],
                    ),
                ),
                dbc.Card(
                    dbc.CardBody(
                        [
                            html.H4(
                                'Sales by Region, Platform and Genre',
                                className='card-title',
                                id=IdHolder.videogame_sales_region_platform_genre_title.name,
                            ),
                            dbc.Spinner(
                                dcc.Graph(
                                    id=IdHolder.videogame_sales_region_platform_genre.name,
                                ),
                            ),
                        ],
                    ),
                ),
            ],
            className='main-grid main-grid--video-game-sales',
        ),
    ],
    className='main-container',
)
